"""migration files updated

Revision ID: 553a5898cc9e
Revises: 
Create Date: 2020-07-25 21:33:07.110985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '553a5898cc9e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), server_default='user', nullable=False),
    sa.Column('password', sa.String(length=128), server_default='password', nullable=False),
    sa.Column('email', sa.String(length=120), server_default='abc@gmail.com', nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_on', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
